version: "1.0"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  accounting-app-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accounting-app-api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres-data:
