'use strict';

const PORT = 3000;

const SUCCESS_CODE = 200;
const SUCCESSFUL_CREATION_CODE = 201;
const SUCCESSFUL_DELETION_CODE = 204;
const NOT_EXIST_CODE = 404;
const INVALID_PARAMETERS_CODE = 400;
const SERVER_SIDE_ERROR_CODE = 500;

module.exports = {
  PORT,
  SUCCESS_CODE,
  SUCCESSFUL_CREATION_CODE,
  SUCCESSFUL_DELETION_CODE,
  NOT_EXIST_CODE,
  INVALID_PARAMETERS_CODE,
  SERVER_SIDE_ERROR_CODE,
};
