'use strict';

const SUCCESS_CODE_STATUS = 200;
const CREATED_CODE_STATUS = 201;
const UNDERSTANDING_CODE_STATUS = 204;
const BAD_REQUEST_CODE_STATUS = 400;
const NOT_FOUND_CODE_STATUS = 404;

module.exports = {
  SUCCESS_CODE_STATUS,
  CREATED_CODE_STATUS,
  UNDERSTANDING_CODE_STATUS,
  BAD_REQUEST_CODE_STATUS,
  NOT_FOUND_CODE_STATUS,
};
